// packages/vue/src/components/Card/Card.vue
<template>
  <div :class="cardClasses">
    <slot />
  </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  size: {
    type: String,
    default: 'md'
  },
  variant: {
    type: String,
    default: 'default'
  },
  liquid: {
    type: Boolean,
    default: false
  },
  interactive: {
    type: Boolean,
    default: false
  }
});

const cardClasses = computed(() => {
  const classes = ['gh-card'];
  
  if (props.size) {
    classes.push(`gh-card-${props.size}`);
  }
  
  if (props.variant) {
    classes.push(`gh-card-${props.variant}`);
  }
  
  if (props.liquid) {
    classes.push('gh-liquid-flow');
  }
  
  if (props.interactive) {
    classes.push('gh-interactive');
  }

  return classes;
});
</script>

// packages/svelte/src/components/GlassCard/Card.svelte
<script lang="ts">
  export let size = 'md';
  export let variant = 'default';
  export let glass = 'medium';
  export let liquid = false;
  export let interactive = false;

  $: cardClasses = [
    'gh-card',
    `gh-card-${size}`,
    `gh-card-${variant}`,
    `gh-glass-${glass}`,
    liquid ? 'gh-liquid-flow' : '',
    interactive ? 'gh-interactive' : ''
  ].filter(Boolean).join(' ');
</script>

<div class={cardClasses}>
  <slot />
</div>
