// packages/vue/src/components/GlassInput/Input.vue
<template>
  <div :class="inputGroupClasses">
    <label v-if="label" :for="inputId" class="gh-input-label">{{ label }}</label>
    
    <div class="gh-input-wrapper">
      <div v-if="icon && iconPosition === 'left'" class="gh-input-icon-left">
        <slot name="icon">{{ icon }}</slot>
      </div>
      
      <input
        :id="inputId"
        :class="inputClasses"
        :type="type"
        :placeholder="placeholder"
        :disabled="disabled"
        :value="modelValue"
        @input="handleInput"
        @focus="handleFocus"
        @blur="handleBlur"
        v-bind="$attrs"
      />
      
      <div v-if="icon && iconPosition === 'right'" class="gh-input-icon-right">
        <slot name="icon">{{ icon }}</slot>
      </div>
      
      <div v-if="button" class="gh-input-button">
        <slot name="button">{{ button }}</slot>
      </div>
    </div>
    
    <div v-if="error" class="gh-input-error">{{ error }}</div>
    <div v-if="help && !error" class="gh-input-help">{{ help }}</div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue';

const props = defineProps({
  modelValue: {
    type: [String, Number],
    default: ''
  },
  type: {
    type: String,
    default: 'text'
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['xs', 'sm', 'md', 'lg', 'xl'].includes(value)
  },
  variant: {
    type: String,
    default: 'default',
    validator: (value) => ['default', 'outline', 'solid'].includes(value)
  },
  glass: {
    type: String,
    default: 'medium',
    validator: (value) => ['light', 'medium', 'heavy'].includes(value)
  },
  liquid: {
    type: Boolean,
    default: false
  },
  error: {
    type: Boolean,
    default: false
  },
  disabled: {
    type: Boolean,
    default: false
  },
  placeholder: {
    type: String,
    default: ''
  },
  label: {
    type: String,
    default: ''
  },
  help: {
    type: String,
    default: ''
  },
  icon: {
    type: [String, Object],
    default: null
  },
  iconPosition: {
    type: String,
    default: 'left',
    validator: (value) => ['left', 'right'].includes(value)
  },
  button: {
    type: [String, Object],
    default: null
  }
});

const emit = defineEmits(['update:modelValue', 'focus', 'blur', 'input']);

const inputId = ref(`input-${Math.random().toString(36).substr(2, 9)}`);

const inputGroupClasses = computed(() => {
  const classes = ['gh-input-group'];
  
  if (props.size) {
    classes.push(`gh-input-group-${props.size}`);
  }
  
  if (props.error) {
    classes.push('gh-input-error-state');
  }
  
  return classes;
});

const inputClasses = computed(() => {
  const classes = ['gh-input'];
  
  if (props.size) {
    classes.push(`gh-input-${props.size}`);
  }
  
  if (props.variant) {
    classes.push(`gh-input-${props.variant}`);
  }
  
  if (props.glass) {
    classes.push(`gh-glass-${props.glass}`);
  }
  
  if (props.liquid) {
    classes.push('gh-liquid-flow');
  }
  
  if (props.error) {
    classes.push('gh-input-error');
  }
  
  if (props.disabled) {
    classes.push('gh-disabled');
  }

  return classes;
});

const handleInput = (event) => {
  emit('update:modelValue', event.target.value);
  emit('input', event);
};

const handleFocus = (event) => {
  emit('focus', event);
};

const handleBlur = (event) => {
  emit('blur', event);
};
</script>

// packages/react/src/components/Input/Input.tsx
import React from 'react';
import './Input.css';

export interface InputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  variant?: 'default' | 'outline' | 'solid';
  glass?: 'light' | 'medium' | 'heavy';
  liquid?: boolean;
  error?: boolean;
  className?: string;
  icon?: React.ReactNode;
  iconPosition?: 'left' | 'right';
  button?: React.ReactNode;
}

export interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  variant?: 'default' | 'outline' | 'solid';
  glass?: 'light' | 'medium' | 'heavy';
  liquid?: boolean;
  error?: boolean;
  className?: string;
}

export interface InputGroupProps {
  children: React.ReactNode;
  className?: string;
  label?: string;
  error?: string;
  help?: string;
  required?: boolean;
}

export interface FloatingLabelProps {
  children: React.ReactNode;
  label: string;
  className?: string;
  error?: string;
  help?: string;
  required?: boolean;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      size = 'md',
      variant = 'default',
      glass = 'medium',
      liquid = false,
      error = false,
      className = '',
      icon,
      iconPosition = 'left',
      button,
      ...props
    },
    ref
  ) => {
    const baseClasses = 'gh-input';
    const sizeClasses = `gh-input-${size}`;
    const variantClasses = variant !== 'default' ? `gh-input-${variant}` : '';
    const glassClasses = `gh-glass-${glass}`;
    const liquidClasses = liquid ? 'gh-input-liquid' : '';
    const errorClasses = error ? 'border-red-500' : '';

    const inputClasses = [
      baseClasses,
      sizeClasses,
      variantClasses,
      glassClasses,
      liquidClasses,
      errorClasses,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    if (icon || button) {
      const containerClasses = [
        icon ? 'gh-input-with-icon' : '',
        button ? 'gh-input-with-button' : '',
        liquidClasses,
      ]
        .filter(Boolean)
        .join(' ');

      return (
        <div className={containerClasses}>
          {icon && (
            <div className={`gh-input-icon ${iconPosition === 'right' ? 'gh-input-icon-right' : ''}`}>
              {icon}
            </div>
          )}
          <input
            ref={ref}
            className={inputClasses}
            {...props}
          />
          {button && (
            <div className="gh-input-button">
              {button}
            </div>
          )}
        </div>
      );
    }

    return (
      <input
        ref={ref}
        className={inputClasses}
        {...props}
      />
    );
  }
);

Input.displayName = 'Input';

const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      size = 'md',
      variant = 'default',
      glass = 'medium',
      liquid = false,
      error = false,
      className = '',
      ...props
    },
    ref
  ) => {
    const baseClasses = 'gh-textarea';
    const sizeClasses = `gh-input-${size}`;
    const variantClasses = variant !== 'default' ? `gh-input-${variant}` : '';
    const glassClasses = `gh-glass-${glass}`;
    const liquidClasses = liquid ? 'gh-input-liquid' : '';
    const errorClasses = error ? 'border-red-500' : '';

    const classes = [
      baseClasses,
      sizeClasses,
      variantClasses,
      glassClasses,
      liquidClasses,
      errorClasses,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <textarea
        ref={ref}
        className={classes}
        {...props}
      />
    );
  }
);

Textarea.displayName = 'Textarea';

const InputGroup = React.forwardRef<HTMLDivElement, InputGroupProps>(
  ({ children, className = '', label, error, help, required, ...props }, ref) => {
    const classes = ['gh-input-group', className].filter(Boolean).join(' ');

    return (
      <div ref={ref} className={classes} {...props}>
        {label && (
          <label className="gh-input-label">
            {label}
            {required && <span className="text-red-500 ml-1">*</span>}
          </label>
        )}
        {children}
        {error && <div className="gh-input-error">{error}</div>}
        {help && !error && <div className="gh-input-help">{help}</div>}
      </div>
    );
  }
);

InputGroup.displayName = 'InputGroup';

const FloatingLabel = React.forwardRef<HTMLDivElement, FloatingLabelProps>(
  ({ children, label, className = '', error, help, required, ...props }, ref) => {
    const classes = ['gh-input-floating', className].filter(Boolean).join(' ');

    return (
      <div ref={ref} className={classes} {...props}>
        {children}
        <label className="gh-input-label">
          {label}
          {required && <span className="text-red-500 ml-1">*</span>}
        </label>
        {error && <div className="gh-input-error">{error}</div>}
        {help && !error && <div className="gh-input-help">{help}</div>}
      </div>
    );
  }
);

FloatingLabel.displayName = 'FloatingLabel';

export { Input, Textarea, InputGroup, FloatingLabel };
